sudo: false
language: bash
os: linux
dist: trusty

matrix:
  include:
    - env:
      - BUILD_TYPE=build
    - env:
      - BUILD_TYPE=platformio
    - env:
      - BUILD_TYPE=docs
#    - env:
#      - BUILD_TYPE=package
    - env:
      - BUILD_TYPE=host_tests

install:
  - pip install --user -r doc/requirements.txt

script:
  - $TRAVIS_BUILD_DIR/tests/common.sh

notifications:
  email:
    on_success: change
    on_failure: change
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/
#    on_success: change  # options: [always|never|change] default: always
#    on_failure: always  # options: [always|never|change] default: always
#    on_start: false     # default: false
