sudo: false
language: bash
os: linux
dist: trusty

cache:
  directories:
    - $HOME/astyle

matrix:
  include:
    - env:
      - BUILD_TYPE=build
    - env:
      - BUILD_TYPE=platformio
    - env:
      - BUILD_TYPE=docs
#    - env:
#      - BUILD_TYPE=package
    - env:
      - BUILD_TYPE=host_tests
    - env:
      - BUILD_TYPE=style_check

install:
  - >
      [ "$BUILD_TYPE" = "docs" ] && {
        pip install --user -r doc/requirements.txt;
      } || true
  - >
      [ "$BUILD_TYPE" = "style_check" ] && {
        [ -f $HOME/astyle/build/gcc/bin/astyle ] || {
          wget -O astyle_3.1_linux.tar.gz https://sourceforge.net/projects/astyle/files/astyle/astyle%203.1/astyle_3.1_linux.tar.gz/download;
          tar -xf astyle_3.1_linux.tar.gz -C $HOME;
          make -C $HOME/astyle/build/gcc;
        }
        make -C $HOME/astyle/build/gcc prefix=$HOME install;
      } || true

script:
  - $TRAVIS_BUILD_DIR/tests/common.sh

notifications:
  email:
    on_success: change
    on_failure: change
#  webhooks:
#    urls:
#      - https://webhooks.gitter.im/e/
#    on_success: change  # options: [always|never|change] default: always
#    on_failure: always  # options: [always|never|change] default: always
#    on_start: false     # default: false
